### ISSUE TITLE
Modal confirmation dialogs for .btn-danger buttons

### ISSUE THREAD

**Issue by lucasdavid** [lucasdavid/demosthenes-legacy#4]
All elements with the class `.btn-danger` represent a delicate operation that should be confirmed beforehand. `Twitter-bootstrap` offers an [modal dialog](http://getbootstrap.com/javascript/#modals) feature that can be used as confirmation screen for these elements' operations.

**Comment by 0tho** [comment]
You could also use (Jquery-ui)[http://jqueryui.com/] for dialogs

**Comment by lucasdavid** [comment]
Sounds good. Ill check that out!
